### ISSUE TITLE
Missing R package when installing

### ISSUE THREAD

**Issue by pearl-yu** [xuyiqing/fect_python#1]
Hi,

The installation was successful in a python jupyter notebook with the command 
`! pip install git+https://github.com/xuyiqing/fect_python.git `

But when I `from fect_python import Fect`, it returns the error: 

> PackageNotInstalledError: The R package "lazyeval" is not installed.

I'm not sure if I could install the R package in my python environment. Any suggestion would be helpful. Thanks!

**Comment by xuyiqing** [comment]
Hi I think you'll probably need to install it in R. In R, try:

> install.packages("lazyeval")
